spring:
  application:
    name: authentication-api
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
      url: ${database_url:jdbc:postgresql://174.138.72.45/postgres}
      username: ${db_user:postgres}
      password: ${db_password:root}
      driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${db_ddl_auto:create}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${db_schema:public}
        temp:
          use-jdbc-metadata: false
        ddl_auto: ${db_ddl_auto:create}
        globally_quoted_identifiers: true
    show-sql: false
server:
  port: ${app_port:3001}
  servlet:
    context-path: /api/v1
  error:
    include-message: always
authentication:
  api:
    jwtSecret: ${jwt_secret:77397A244326462948404D635166546A576E5A7234753778214125442A472D4B}
    jwtAccessExpirationMs: ${jwt_access_expiration_ms:604800000} # 7 days